### ISSUE TITLE
CAMT Forschungsergebnisse

### ISSUE THREAD

**Issue by c-alpha** [Konafets/mo-bank-import-definitions#1]
Ich hab mal mit ein paar CAMT Beispieldateien (gibt's bei vielen Banken auf der Website) etwas experimentiert, und über die Spaltenzuordnung bislang folgende Erkenntnisse gewonnen:

**CAMT.052**
```
' Spalte_001 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/ValDt/Dt                                     (Wertstellungsdatum)
' Spalte_002 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/Amt                                          (Buchungsbetrag mit Vorzeichen)
' Spalte_003 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/Amt/@Ccy                                     (Währung Buchungsbetrag)
' Spalte_004 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/NtryDtls/TxDtls/RmtInf/Ustrd                 (Buchungstext)
               /Document/BkToCstmrAcctRpt/Rpt/Ntry/NtryDtls/TxDtls/AddtlTxInf
' Spalte_005 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/NtryDtls/TxDtls/RltdPties/Dbtr/Nm            (Auftraggeber Name)
' Spalte_006 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/NtryDtls/TxDtls/RltdPties/DbtrAcct/Id/IBAN   (Auftraggeber IBAN)
' Spalte_007 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/NtryDtls/TxDtls/Refs/EndToEndId              (Ende-zu-Ende ID)
' Spalte_008 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/NtryRef                                      (Bankreferenz)
               /Document/BkToCstmrAcctRpt/Rpt/Ntry/NtryDtls/TxDtls/Refs/AcctSvcrRef
' Spalte_009 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/NtryDtls/TxDtls/RmtInf/Strd/CdtrRefInf/Ref   (RF Structured Creditor Reference; ISO 11649)
' Spalte_010 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/Chrgs/TtlChrgsAndTaxAmt/@Ccy                 (Währung Gebühren; Präfix: "Gebühren: ")
' Spalte_011 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/AddtlNtryInf                                 (Notiz)
' Spalte_012 = /Document/BkToCstmrAcctRpt/Rpt/Ntry/BookgDt/Dt                                   (Buchungsdatum)
' Spalte_013 =
' Spalte_014 =
' Spalte_015 =
' Spalte_016 =
' Spalte_017 =
' Spalte_018 =
' Spalte_019 =
' Spalte_020 =
```

**CAMT.053**
```
' Spalte_001 = /Document/BkToCstmrStmt/Stmt/Ntry/ValDt/Dt                                       (Wertstellungsdatum)
' Spalte_002 = /Document/BkToCstmrStmt/Stmt/Ntry/Amt                                            (Buchungsbetrag mit Vorzeichen)
' Spalte_003 = /Document/BkToCstmrStmt/Stmt/Ntry/Amt/@Ccy                                       (Währung Buchungsbetrag)
' Spalte_004 = /Document/BkToCstmrStmt/Stmt/Ntry/NtryDtls/TxDtls/RmtInf/Ustrd                   (Buchungstext)
' Spalte_005 = /Document/BkToCstmrStmt/Stmt/Ntry/NtryDtls/TxDtls/RltdPties/Dbtr/Nm              (Auftraggeber Name)
' Spalte_006 = /Document/BkToCstmrStmt/Stmt/Ntry/NtryDtls/TxDtls/RltdPties/DbtrAcct/Id/IBAN     (Auftraggeber IBAN)
' Spalte_007 = /Document/BkToCstmrStmt/Stmt/Ntry/NtryDtls/TxDtls/Refs/EndToEndId                (Ende-zu-Ende ID)
' Spalte_008 = /Document/BkToCstmrStmt/Stmt/Ntry/NtryRef                                        (Bankreferenz)
               /Document/BkToCstmrStmt/Stmt/Ntry/NtryDtls/TxDtls/Refs/AcctSvcrRef
' Spalte_009 = /Document/BkToCstmrStmt/Stmt/Ntry/NtryDtls/TxDtls/RmtInf/Strd/CdtrRefInf/Ref     (RF Structured Creditor Reference; ISO 11649)
' Spalte_010 = /Document/BkToCstmrStmt/Stmt/Ntry/Chrgs/TtlChrgsAndTaxAmt/@Ccy                   (Währung Gebühren; Präfix: "Gebühren: ")
' Spalte_011 = /Document/BkToCstmrStmt/Stmt/Ntry/AddtlNtryInf                                   (Notiz)
' Spalte_012 = /Document/BkToCstmrStmt/Stmt/Ntry/BookgDt/Dt                                     (Buchungsdatum)
' Spalte_013 =
' Spalte_014 =
' Spalte_015 =
' Spalte_016 =
' Spalte_017 =
' Spalte_018 =
' Spalte_019 =
' Spalte_020 =
```

Allerdings sind die Ergebnisse nicht immer konsistent. Das könnte darauf hindeuten, daß MO evtl. weitere Plausibilitätsprüfungen vornimmt (und deshalb manche Werte verwirft), oder daß man den Importprozeß noch irgendwie steuern/konfigurieren muß.

**Comment by Konafets** [comment]
Moin @c-alpha,

danke für Dein Nachforschen. Kannst Du hier ein paar Beispiele verlinken, damit ich das mir mal anschauen kann?

Ich stelle mir allerdings die Frage, ob CAMT.052 überhaupt in MO unterstützt bzw. ob das zielführend ist zu unterstützen. Wie hier https://www.moneytoday.ch/lexikon/camt/ zu lesen ist, bezieht sich das auf Intraday Reports und ich möchte ja Kontoauszüge (camt.053) importieren.

**Comment by c-alpha** [comment]
Stefano Kowalke <notifications@github.com> writes:

> [...]
> danke für Dein Nachforschen. Kannst Du hier ein paar Beispiele
> verlinken, damit ich das mir mal anschauen kann?

Beispiele wovon/wofür?

> Ich stelle mir allerdings die Frage, ob CAMT.052 überhaupt in MO
> unterstützt bzw. ob das zielführend ist zu unterstützen.

Wenn Du auf "Importdefinitionen für Bankauszüge" > "Verwalten" > "Neu"
gehst, kannst Du als Format neben "Text", und "CSV" auch "CAMT.052" und
"CAMT.053" auswählen.

> Wie hier https://www.moneytoday.ch/lexikon/camt/ zu lesen ist, bezieht
> sich das auf Intraday Reports und ich möchte ja Kontoauszüge
> (camt.053) importieren.

CAMT.052 und 053 sind einigermaßen ähnlich. 052 ist etwas einfacher, da
es wie Du sagst für ad-hoc Abfragen gedacht ist. 053 enthält einen oder
mehrere Kontoauszüge, und ist dazu gedacht die "normalen", monatlichen
Kontoauszüge zu übermitteln. Das Format einer einzelnen Transaktion in
beiden Formaten ist nahezu identisch.

MO ignoriert das "Beiwerk" drumrum, und liest nur diese Transaktionen
ein. Die semantische Zurodnung Inhalt -> Spalte_XYZ scheint in beiden
CAMT Formaten identisch zu sein.

Allerdings haben viele Banken in Ländern unterschiedliche Profile von
CAMT.052 und 053 definiert (und halten sich mehr weniger daran). Je
nachdem, wie ich meine Testdaten erzeuge, sind bestimmte Spalte_XYZ mal
ausgefüllt, und mal nicht. Ich gehe daher davon aus, daß die
Dienstleistung "Importdefinition für XML erstellen" die Anpassung an ein
solches Profil (nebst Implementierungseigenehiten seitens der Bank)
beinhaltet.

Ich habe daher meine Recherche wieder eingestellt. Wer auf CAMT.052/053
Import angewiesen ist, für den sollten m.E. die knapp 50,- gut
investiert sein. Andernfalls mit Text, oder CSV arbeiten; da hat man
volle Kontrolle.

**Comment by Konafets** [comment]
Hier noch ein Link zu Beispieldaten in beiden Formaten:

https://www.sepa-tools.de/camt-testdateien.html

Bei Gelegenheit schau ich mir das mal genauer an.
